# Generated by Django 6.0.5 on 2026-05-30 07:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image_one', models.ImageField(upload_to='portfolio')),
                ('image_two', models.ImageField(upload_to='portfolio/detail')),
                ('image_three', models.ImageField(upload_to='portfolio/detail')),
                ('image_four', models.ImageField(upload_to='portfolio/detail')),
                ('image_five', models.ImageField(upload_to='portfolio/detail')),
                ('client_name', models.CharField(max_length=25)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('asign_to', models.CharField(max_length=30)),
                ('challenge_title', ckeditor.fields.RichTextField()),
                ('story', ckeditor.fields.RichTextField()),
                ('approach', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
