# Generated by Django 6.0.5 on 2026-05-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_portfolio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='short_discription',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
