# Generated by Django 6.0.5 on 2026-05-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_portfolio_short_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='short_discription',
            field=models.CharField(max_length=250),
        ),
    ]
