# Generated by Django 6.0.5 on 2026-05-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_portfolio_short_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(upload_to='banner_port')),
                ('image_two', models.ImageField(upload_to='banner_port')),
                ('image_three', models.ImageField(upload_to='banner_port')),
            ],
        ),
    ]
