# Generated by Django 6.0.5 on 2026-05-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_two',
        ),
    ]
